server:
  port: 8083

spring:
  application:
    name: transaction-service
  config:
    import: optional:configserver:http://config-server:8888

account-service:
  url: http://account-service

resilience4j:
  retry:
    instances:
      accountService:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
  circuitbreaker:
    instances:
      accountService:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
  thread-pool-bulkhead:
    instances:
      transferOperation:
        max-thread-pool-size: 15
        core-thread-pool-size: 8
        queue-capacity: 20
        keep-alive-duration: 20ms