server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: account-service
              uri: lb://account-service
              predicates:
                - Path=/api/accounts/**
              filters:
                - StripPrefix=1

            - id: customer-service
              uri: lb://customer-service
              predicates:
                - Path=/api/customers/**
              filters:
                - StripPrefix=1

            - id: transaction-service
              uri: lb://transaction-service
              predicates:
                - Path=/api/transactions/**
              filters:
                - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/